### ISSUE TITLE
Unable to configure Mark, Space and Pause duration

### ISSUE THREAD

**Issue by tacarrie** [Fortyseven/ToneDef#19]
With the Release 19, it is not possible to change the Mark, Space and Pause duration anymore. When opening the corresponding menu item in the Config, a pop-up window with no edit field appears (see attached screenshot).
![Screenshot_20190812-091044_ToneDef](https://user-images.githubusercontent.com/10333743/62849920-b2816a00-bce1-11e9-89a3-2cb7a3137b97.jpg)

**Comment by Fortyseven** [comment]
_Damn._ I have a theory on that, though -- I'll check into it in the morning. Thank you!

**Comment by Fortyseven** [comment]
Fixed in 20? 🤞
