### ISSUE TITLE
RFC: Considering removing contact integration

### ISSUE THREAD

**Issue by Fortyseven** [Fortyseven/ToneDef#23]
I'm considering removing the ability to dial via contacts. 

I'm unsure if anyone is actually **using** this feature. And while it seemed like it might be useful, initially, the necessity of requiring permissions to access contacts has put some folks off of using it. (As a guy paranoid of permissions of strange apps, myself, I completely sympathize. 😏)

If I get rid of the feature, I can remove the permission. 

However, if even a couple people are using it and find it helpful, I don't have a problem maintaining the status quo and leaving it as-is.  I just don't want to keep it around if nobody is using it.

**Comment by kj7rrv** [comment]
I do use it occasionally, but I wouldn't really care if it went away.

Would it be possible to have it as an opt-in feature and have the app only ask for the permission when it was used?

**Comment by Fortyseven** [comment]
As long as I know even one person is using that feature, I won't touch it. :)  Just doing some 'spring cleaning'. 😎
