### ISSUE TITLE
Italian ringback tone is wrong

### ISSUE THREAD

**Issue by LuccoJ** [Fortyseven/ToneDef#6]
What the application calls "RINGBACK [IT]" actually sounds like the Italian dial tone. The Italian ringback tone sounds pretty much, if not exactly, like "RINGBACK [EUROPE]". Even then, I think "RINGBACK [IT]" is slightly faster than the real Italian dial tone.

**Comment by Fortyseven** [comment]
Good catch, thanks! :) I pulled up some documentation on this, and implemented the (hopefully) correct ringback, and added the dialtone, too. (I really need to rewrite that whole section. It's a mess.)

I'll do what I can to verify them before pushing the fix into the next release.

My references: 
- http://nemesis.lonestar.org/reference/telecom/signaling/dialtone.html
- http://nemesis.lonestar.org/reference/telecom/signaling/ringring.html

**Comment by Fortyseven** [comment]
Should be fixed now. I wound up rewriting the entire section, like I threatened. ;D Let me know how it sounds! I took the tone data directly from a database of international tones, so if that's accurate, it should be here, too. If it's not, I'll see what I can do.
